Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.define "master0" do |master0|
    master0.vm.provider "virtualbox" do |master0vbox|
      master0vbox.name = "devops_together-project_torgiren-master0"
    end
    master0.vm.hostname = 'master0'
    master0.vm.network "private_network",  name: "vboxnet1", ip: "192.168.57.10"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ['modifyvm', :id, '--description', '{"key": "value"}']
  end


  config.vm.box = "ubuntu/jammy64"
  
  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false
  config.ssh.keys_only = false
  config.ssh.forward_agent = true
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]

  config.vm.provision :shell, privileged: false do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
       echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
    SHELL
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.verbose = "v"
  #   ansible.playbook = "playbook.yml"
  # end
end
