# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.0"
require 'json'
machines_vag = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'machines_vagrant.json')))

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	machines_vag.each do |machines|
		config.vm.define machines['name']  do |mav|
			mav.vm.box = machines['box']
			mav.vm.hostname = machines['hostname']
			mav.vm.network machines['type_net'], name: machines['name_network'] ,ip: machines['ip']
			mav.vm.provider :virtualbox do |vb|
				vb.name = machines['name']
				vb.customize ["modifyvm", :id, "--cpus", machines['vcpu']]
				vb.memory = machines['ram']
			end
			if Vagrant.has_plugin?("vagrant-vbguest") then
				config.vbguest.auto_update = false
			end
			mav.vm.provision "ansible" do |ansible|
				ansible.verbose = "v"
				ansible.playbook = machines['playbooks']
			end
		end
	end
end
