all:
  hosts:
    master0:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: vagrant
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    rke2_master:
      hosts:
        master0:

