galaxy_info:
  author: goodbit22
  description: The role installs rke2_server on Centos8 systems
  company: None
  license: GPL-2.0
  min_ansible_version: 2.1
  platforms:
    - name: Centos8
      versions:
        - 8
  galaxy_tags: []
  dependencies: []
