---
- name: install rke2-agent
  yum: name=rke2-agent state=latest

- name: copy config.yaml file
  copy:
    src: "./config.yaml"
    dest: "/etc/rancher/rke2/config.yaml"
    mode: u+rw,g-wx,o-rwx

- name: Start service rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started

- name: Enable service rek2-server
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: true
    masked: false
