#checkov:skip:CKV2_GHA_1:Comment
name: DevOps-Together CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
permissions: read-all

jobs:
  linter:
    runs-on: [ubuntu-22.04]
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          ANSIBLE_DIRECTORY: ansible
          VALIDATE_ANSIBLE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_TERRAFORM_TFLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scan:
    runs-on: [ubuntu-22.04]
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: semgrep
        run: semgrep --config auto
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          download_external_modules: true

